name: esds-blog
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.7
  - pip
  - ablog
  - cftime
  - colorspacious
  - dask
  - dask-labextension
  - distributed
  - graphviz
  - ipywidgets
  - jupyterlab>=3
  - matplotlib
  - myst-nb>=0.12.0
  - netcdf4
  - pip
  - pydata-sphinx-theme>=0.4.3
  - python-graphviz
  - python=3.9
  - scipy
  - seaborn
  - sparse
  - sphinx
  - sphinx-autobuild
  - sphinx-comments
  - sphinx-panels
  - sphinxcontrib-bibtex<2.0.0
  - xarray>=0.18.2
  - sphinxext-rediraffe
  - sphinx-design
  - sphinx-copybutton
  - pip:
      - sphinxext-opengraph
